services:
  littleroot:
    command: bash ./start.bash
    container_name: littleroot
    depends_on:
      - anubis
      - caddy
    image: eclipse-temurin:21-jre
    networks:
      - caddy-littleroot
    ports:
      - 25571:25571
    restart: unless-stopped
    stdin_open: true
    tty: true
    user: 1000:1000
    volumes:
      - ./volumes/server:/server

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    working_dir: /server
